### ISSUE TITLE
Using GPU with TensorFlow

### ISSUE THREAD

**Issue by hadim** [imagej/imagej-tensorflow#9]
At the moment the GPU can only be used on Linux with Java TensorFlow: https://www.tensorflow.org/versions/master/install/install_java#gpu_support

Windows support will come soon (they are actively working on it).

The thing is that to enable the GPU on Linux the Maven imports need to be different:

```xml
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>libtensorflow</artifactId>
  <version>1.7.0-rc1</version>
</dependency>
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>libtensorflow_jni_gpu</artifactId>
  <version>1.7.0-rc1</version>
</dependency>
```

It's important to note that GPU won't be enabled with `<artifactId>libtensorflow</artifactId>` in the POM (even if it's a parent POM).

Also, I noted that TF can't find the CUDA libs in `/usr/local/cuda` if I don't start Eclipse from the command line (where I have `LD_LIBRARY_PATH` correctly set in my `.bash_profile`).

Note that on Python TF ships with-GPU and without-GPU Python packages which mean that GPU can't be discovered during runtime.

So I can't really think of a good way to deal with it. In an ideal world, all ImageJ packages will have the same build and load the correct dependency at runtime according to the platform and the presence of a GPU. But I think it's kind of a dream at the moment.

Anyway, I just wanted to let you know that in case you have comments.

**Comment by ctrueden** [comment]
Maven is a build tool. It does not fully solve deployment. You do not need `libtensorflow_jni_gpu` to build. What is needed to make GPU work at runtime is a deployment that includes the correct native artifacts. The reason to declare things in a Maven POM at `runtime` scope is to document that they are necessary and/or desirable for the project to function optimally at runtime. Maven has some limited support for synthesizing a simple runtime environment based on the project's dependencies, so that e.g. you can run from an IDE or via (in the case of SciJava projects) `mvn -Pexec` on the command line. But these are not the intended primary deployment vehicles. In the case of GPU support for TensorFlow within ImageJ, we just need to ship the correct natives in the correct `jars/<platform>` and/or `lib/<platform>` directories. The only real "problem" to solve, IMHO, is how to make the imagej-maven-plugin's `copy-jars` goal smart enough to populate an ImageJ installation in a cross-platform way. But this problem is not specific to imagej-tensorflow.

**Comment by hadim** [comment]
Oh, I see so it seems to be simpler to solve than what I was thinking.

Since it's not specific to this repo, I close here.
